sudo: false

language: node_js

env:
  global:
    # @MoOx token for francejs/ToulouseJS
    - secure: "xe7wxg2VNmH2JqHr2/pu/noHs2NoSU3iFyrkEut0G3pWEeaMlTGxuKcAeQzwaJftzK+PzXgXr1J2LBvGTA/UWd9t2BZYYjmvsYVHlwCFxqAZry+bALi6to5rjTBX4uPyK3h4Tm7EdtVX+bdfdI8jJcjf9Nc
/QmKYtDTcwJkDoIU="
