sudo: false

language: node_js

# http://docs.travis-ci.com/user/build-configuration/
script:
  # we need --global because of how gulp-gh-pages works (with another clone elsewhere)
  - git config --global user.name "Travis-CI"
  - git config --global user.email "bot@travis-ci.org"
  - npm run travis

env:
  global:
    # @MoOx token for francejs/ToulouseJS
    - secure: "xe7wxg2VNmH2JqHr2/pu/noHs2NoSU3iFyrkEut0G3pWEeaMlTGxuKcAeQzwaJftzK+PzXgXr1J2LBvGTA/UWd9t2BZYYjmvsYVHlwCFxqAZry+bALi6to5rjTBX4uPyK3h4Tm7EdtVX+bdfdI8jJcjf9Nc
/QmKYtDTcwJkDoIU="
