sudo: false

language: node_js
node_js:
  - '6'
  - '5'

# (by default, Travis will run "npm test" script when the language is node_js)

# deploy is run after "npm test"
deploy:
  # keep the build we just made with "npm test" (dist/)
  skip_cleanup: true

  # define the script to use for deployment
  provider: script
  script: ./scripts/deploy.sh

  # only run on one version of node (v6 here)
  on:
    branch: master # ⚠️ OR SRC IF YOU USE USERNAME.GITHUB.IO
    node: '6'

env:
  global:
    # @MoOx token for francejs/ToulouseJS
    - secure: >-
        vmBZf+ikTdnGKR8pV4OWejNf872eINRkor9k6Xt71A5dCbQlVqVm+aFse7aE32wpK45jBjZJTpCRBffsJU3ZCU5Y9Jiu3mHDNTc3wh2IyQ9zUES445yNK9SSsI7vyn+twU4NxZa+3R+0DStTuXjeIona4AyWzmwyc5tUXiRoFYI=
